version: '3'
services:
  cas-server:
    image:  memeater
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: memeater
    #    restart: always
    volumes:
    - /etc/localtime:/etc/localtime
